services:
  ytm-downloader:
    image: raymanalang/ytm-downloader:latest
    container_name: ytm-downloader
    restart: unless-stopped
    ports:
      - "8503:8080"
    volumes:
      - /share:/share
    environment:
      DOWNLOADS_DIR: /share
      DB_PATH: /share/ytm-downloader/downloads.db
      MAX_CONCURRENT_DOWNLOADS: "2"
